apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "mabenoit-nodeserice-2"
  annotations:
    "humanitec.com/orgId": "workshop-kubecon-london"
    "humanitec.com/appId": "mabenoit-nodeserice-2"
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
